const menuItems = [
  {
    id: 1,
    name: "Bebida caliente",
    description: "Delicious tacos",
    price: 12.99,
    image: "./public/imagen/bebidas_calientes1.PNG",
    region: "Latinoamérica",
  },
  {
    id: 2,
    name: "carne",
    description: "Thick griddle cakes",
    price: 9.99,
    image: "/public/imagen/mexica1.jpg",
    region: "Centroamérica",
  },
  {
    id: 3,
    name: "Ceviche",
    description: "Fresh seafood",
    price: 15.99,
    image: "https://via.placeholder.com/150",
    region: "Suramérica",
  },
  {
    id: 4,
    name: "Ceviche",
    description: "Fresh seafood",
    price: 15.99,
    image: "https://via.placeholder.com/150",
    region: "Suramérica",
  },
  {
    id: 5,
    name: "Ceviche",
    description: "Fresh seafood",
    price: 15.99,
    image: "https://via.placeholder.com/150",
    region: "Suramérica",
  },
  {
    id: 6,
    name: "Ceviche",
    description: "Fresh seafood",
    price: 15.99,
    image: "https://via.placeholder.com/150",
    region: "Suramérica",
  },
  {
    id: 7,
    name: "Lechona",
    description: "plátanos rellenos",
    price: 15.99,
    image: "./public/imagen/mexica2.jpg",
    region: "Suramérica",
  },
  {
    id: 8,
    name: "Sancocho",
    description: "Fresh seafood",
    price: 15.99,
    image: "./public/imagen/sancocho.webp",
    region: "Suramérica",
  },
];

const productos = [
  

  {
    id: 7,
    precio: 90000,
    nombre: "Postre",
    img: "./public/imagen/postre2.PNG",
    descripcion: "ya nhhjshhshao ",
    descripcion1: "Sabor y dulsura en el plato",
  },
  {
    id: 8,
    precio: 10000,
    nombre: "Coltel",
    img: "./public/imagen/coltel.webp",
    descripcion: "Los tacos son uno de comida ",
    descripcion1: "tanos",
  },

  {
    id: 10,
    precio: 30000,
    nombre: "Cerveza",
    img: "./public/imagen/cervezas.webp",
    descripcion: "La lechona es un conoce como ",
    descripcion1: "plátanos rellenos",
  },
  {
    id: 9,
    precio: 100,
    nombre: "plátanos rellenos",
    img: "./public/imagen/platano.PNG",
    descripcion: "ya no kkkkk",
    descripcion1: "Rellenos de bocadillo y queso",
  },
  {
    id: 10,
    precio: 30000,
    nombre: "Jugos",
    img: "./public/imagen/JUGOS_NATURALES.jpg",
    descripcion: "La lechona es unente se conoce como ",
    descripcion1: "plátanos rellenos",
  },
  {
    id: 11,
    precio: 90000,
    nombre: "Arrozanas",
    img: "./public/imagen/mexico6.jpg",
    descripcion: "ya nhhjshhshao ",
    descripcion1: "plátanos rellenos",
  },
  {
    id: 11,
    precio: 90000,
    nombre: "Licor",
    img: "./public/imagen/licores.webp",
    descripcion: "ya nhhjshhshao ",
    descripcion1: "plátanos rellenos",
  },
];
